deploy:
  type: git
  repo: <repository url>
  branch: [branch]
  token: ''
  message: [message]
  name: [git user]
  email: [git email]
  extend_dirs: [extend directory]
  ignore_hidden: true # default is true
  ignore_pattern: regexp  # whatever file that matches the regexp will be ignored when deploying
